kuka:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 2.0
  kinematics_solver_attempts: 2
  mode: global
  position_threshold: 0.0001
  orientation_threshold: 0.0005
  cost_threshold: 1.0
  position_scale: 1.0
  rotation_scale: 0.5
  avoid_joint_limits_weight: 0.001
  minimal_displacement_weight: 0.001
  stop_optimization_on_valid_solution: false
  memetic_num_threads: 4
  memetic_stop_on_first_solution: false
