<?xml version="1.0"?>
<package format="3">
  <name>kcg_connector</name>
  <version>0.1.0</version>
  <description>Isaac Sim task logic for KUKA iiwa and KCG hand connector assembly.</description>
  <maintainer email="974622934@qq.com">dong</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>iiwa_description</exec_depend>
  <exec_depend>kcg_moveit1</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>xacro</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
